name: dark_light_button
description: A package containing ready to use widgets for switching between dark and light theme
version: 0.0.1+4
homepage: https://github.com/xoltawn/dark_light_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sprung: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/dark_light_button/assets/images/night.png
    - packages/dark_light_button/assets/images/day.png